name: mml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.20=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - ipykernel=7.2.0=pyha191276_1
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgomp=15.2.0=he0feb66_17
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - parso=0.8.6=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=26.0.1=pyh8b19718_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py310h139afa4_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.0=h543edf9_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.2=h04a0ce9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h366c992_103
  - tornado=6.5.4=py310ha78b2d2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zeromq=4.3.5=h387f397_9
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.4.0
      - astropy==6.1.7
      - astropy-iers-data==0.2026.2.9.0.50.33
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - bilby==2.7.1
      - bilby-cython==0.5.3
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - configparser==7.2.0
      - contourpy==1.3.2
      - corner==2.2.3
      - cryptography==46.0.5
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.4
      - cycler==0.12.1
      - cython==3.2.4
      - dateparser==1.3.0
      - denmarf==0.3.2
      - dill==0.4.1
      - dqsegdb2==1.3.0
      - dynesty==3.0.0
      - emcee==3.1.6
      - filelock==3.21.2
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - geopandas==1.1.2
      - getdist==1.7.5
      - gwdatafind==2.1.1
      - gwosc==0.8.1
      - gwpy==3.0.14
      - gwsnr==0.4.5
      - h5py==3.15.1
      - idna==3.11
      - igwn-auth-utils==1.4.0
      - igwn-ligolw==2.0.1
      - igwn-segments==2.1.1
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lalsuite==7.26.4
      - lazy-loader==0.4
      - lenstronomy==1.13.5
      - ler==0.5.3
      - libpysal==4.13.0
      - ligotimegps==2.0.1
      - llvmlite==0.46.0
      - lscsoft-glue==4.1.1
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpld3==0.5.12
      - mpmath==1.3.0
      - multiprocess==0.70.19
      - networkx==3.4.2
      - numba==0.63.1
      - numdifftools==0.9.42
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.4.127
      - pandas==2.3.3
      - pegasus-wms-api==5.1.2
      - pegasus-wms-common==5.1.2
      - pillow==12.1.1
      - platformdirs==4.7.0
      - pointpats==2.5.2
      - pycbc==2.9.0
      - pycparser==3.0
      - pyerfa==2.0.1.5
      - pyjwt==2.11.0
      - pykerr==0.2.0
      - pyogrio==0.12.1
      - pyparsing==3.3.2
      - pyproj==3.7.1
      - pytz==2025.2
      - pyxdg==0.28
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - safe-netrc==1.0.1
      - schwimmbad==0.4.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scitokens==1.8.1
      - shapely==2.1.2
      - soupsieve==2.8.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.5.0
      - tqdm==4.67.3
      - triton==3.1.0
      - tzdata==2025.3
      - tzlocal==5.3.1
      - urllib3==2.6.3
prefix: /home/hedge/miniconda3/envs/mml
